// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTAyB6JgC5Hb097I2Md0hQHi2QQj6GZD0',
    appId: '1:72969643027:web:e5fc9130ca324146a64be6',
    messagingSenderId: '72969643027',
    projectId: 'restaurant-menu-244ab',
    authDomain: 'restaurant-menu-244ab.firebaseapp.com',
    databaseURL: 'https://restaurant-menu-244ab.firebaseio.com',
    storageBucket: 'restaurant-menu-244ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdw9Prpz9GRLXB9LBk0vGafX2FSffdyd4',
    appId: '1:72969643027:android:066d27a14928d89ea64be6',
    messagingSenderId: '72969643027',
    projectId: 'restaurant-menu-244ab',
    databaseURL: 'https://restaurant-menu-244ab.firebaseio.com',
    storageBucket: 'restaurant-menu-244ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7kDQFvjThRSnSHHOMioWCWQSAdKTs0hs',
    appId: '1:72969643027:ios:1ac3850fd28cbacfa64be6',
    messagingSenderId: '72969643027',
    projectId: 'restaurant-menu-244ab',
    databaseURL: 'https://restaurant-menu-244ab.firebaseio.com',
    storageBucket: 'restaurant-menu-244ab.appspot.com',
    androidClientId:
        '72969643027-1hpn8i12a6upb0ate125lfu42c15glfl.apps.googleusercontent.com',
    iosClientId:
        '72969643027-mijf1kjf2o86s58totfrrd96rhl7p0hj.apps.googleusercontent.com',
    iosBundleId: 'com.bingkaiapp.restoresto',
  );
}
